Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),

    #----------------------------banner-----------------------------------
    path('banner-list/', views.list_banner, name='banner_list'),
    path('banner-create/', views.create_banner, name='banner_create'),
    path('banner-detail/<int:id>/', views.detail_banner, name='banner_detail'),
    path('banner-edit/<int:id>/', views.edit_banner, name='banner_edit'),
    path('banner-delete/<int:id>/', views.delete_banner, name='banner_delete'),
    # ------------------------service----------------------------
    path('service-list/', views.list_service, name='service_list'),
    path('service-create/', views.create_service, name='service_create'),
    path('service-detail/<int:id>/', views.detail_service, name='service_detail'),
    path('service-edit/<int:id>/', views.edit_service, name='service_edit'),
    path('service-delete/<int:id>/', views.delete_service, name='service_delete'),
    #-----------------------price---------------------------------------
    path('price-list/', views.list_price, name='price_list'),
    path('price-create/', views.create_price, name='price_create'),
    path('price-detail/<int:id>/', views.detail_price, name='price_detail'),
    path('price-edit/<int:id>/', views.edit_price, name='price_edit'),
    path('price-delete/<int:id>/', views.delete_price, name='price_delete'),
    #--------------------------------about-------------------------------
    path('about-list/', views.list_about, name='about_list'),
    path('about-create/', views.create_about, name='about_create'),
    path('about-detail/<int:id>/', views.detail_about, name='about_detail'),
    path('about-edit/<int:id>/', views.edit_about, name='about_edit'),
    path('about-delete/<int:id>/', views.delete_about, name='about_delete'),
    #---------------------------------contact--------------------------------------
    path('contact-list/', views.list_contact, name='contact_list'),
    path ('contact-detail/<int:id>/', views.detail_contact, name='contact_detail'),
    path('contact-edit/<int:id>/', views.edit_contact, name='contact_edit'),
    # -----------------register, login, logout-------------------------------
    path('register/', views.register, name='register'),
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),
    # ----------------search--------------
    path('q', views.query, name='query')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('service/', views.service, name='service'),
    path('about/', views.about, name='about'),
    path('price/', views.price, name='price'),
]

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from main import models
from django.contrib import messages
from django.db.models import Q

@login_required(login_url='dashboard:log_in')
def index(request):
    contacts = models.Contact.objects.filter(is_show=False).count()
    data_1 = [1,2,3,4,5,6,7]
    data_2 = [2,3,4,5,6,7,8]
    context = {
        'contacts':contacts,

        'data_1':data_1,
        'data_2':data_2,
    }
    return render(request, 'dashboard/index.html', context)



@login_required(login_url='dashboard:log_in')
def create_banner(request):
    if request.method == "POST":
        try:
            title = request.POST['title']
            body = request.POST['body']
            models.Banner.objects.create(
                title=title,
                body=body,
            )
            messages.success(request, 'Banner muvaffaqiyatli yaratilindi')
        except:
            messages.error(request, 'Banner yaratilishda xatolik')


    return render(request, 'dashboard/banner/create.html')


@login_required(login_url='dashboard:log_in')
def list_banner(request):
    banners = models.Banner.objects.all()
    context = {
        'banners':banners
    }
    return render(request, 'dashboard/banner/list.html', context)

def detail_banner(request, id):
    banner = models.Banner.objects.get(id=id)
    context = {
        'banner':banner
    }
    return render(request, 'dashboard/banner/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_banner(request, id):
    banner = models.Banner.objects.get(id=id)
    if request.method =='POST':
        try:
            banner.title = request.POST['title']
            banner.body = request.POST['body']
            banner.save()
            messages.success(request, 'Banner muvaffaqiyatli o`zgartirildi')
        except:
            messages.error(request, 'Banner o`zgartirishda xatolik')
        return redirect('dashboard:banner_detail', banner.id)
    context = {
        'banner':banner
    }
    return render(request, 'dashboard/banner/edit.html', context)

def delete_banner(request, id):
    try:
        models.Banner.objects.get(id=id).delete()
        messages.error(request, 'Banner o`chirildi')
    except:
        messages.error(request, 'Banner o`chirishda xatolik')
    return redirect('dashboard:banner_list')



@login_required(login_url='dashboard:log_in')
def create_service(request):
    if request.method == "POST":
        try:
            name = request.POST['name']
            body = request.POST['body']
            icon = request.POST['icon']
            models.Service.objects.create(
                name=name,
                body=body,
                icon=icon
            )
            messages.success(request, 'Servis muvaffaqqiyatli yaratildi')
        except:
            messages.error(request, 'Servis yaratishda xatolik')
    return render(request, 'dashboard/service/create.html')


@login_required(login_url='dashboard:log_in')
def list_service(request):
    services = models.Service.objects.all()
    context = {
        'services':services
    }
    return render(request, 'dashboard/service/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_service(request, id):
    service = models.Service.objects.get(id=id)
    context = {
        'service':service
    }
    return render(request, 'dashboard/service/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_service(request, id):
    service = models.Service.objects.get(id=id)
    if request.method =='POST':
        try:
            service.name = request.POST['name']
            service.body = request.POST['body']
            service.icon = request.POST['icon']
            service.save()
            messages.success(request, 'Servis muvaffaqqiyatli o`zgartirildi')
        except:
            messages.error(request, 'Servis o`zgartirishda xatolik')

        return redirect('dashboard:service_list', service.id)
    context = {
        'service':service
    }
    return render(request, 'dashboard/service/edit.html', context)


@login_required(login_url='dashboard:log_in')
def delete_service(request, id):
    try:
        models.Service.objects.get(id=id).delete()
        messages.error(request, 'Servis muvaffaqqiyatli o`chirildi')
    except:
        messages.error(request, 'Servis o`chirishda xatolik')
    return redirect('dashboard:service_list')


@login_required(login_url='dashboard:log_in')
def create_price(request):
    if request.method == "POST":
        try:
            title = request.POST['title']
            price = request.POST['price']
            body = request.POST['body']
            models.Price.objects.create(
                title=title,
                price=price,
                body=body
            )
            messages.success(request, 'Price muvaffaqqiyatli yaratildi.')
        except:
            messages.error(request, 'Price yaratishda xatolik')
    return render(request, 'dashboard/price/create.html')


@login_required(login_url='dashboard:log_in')
def list_price(request):
    prices = models.Price.objects.all()
    context = {
        'prices':prices
    }
    return render(request, 'dashboard/price/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_price(request, id):
    prices = models.Price.objects.get(id=id)
    context = {
        'prices':prices
    }
    return render(request, 'dashboard/price/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_price(request, id):
    price = models.Price.objects.get(id=id)
    if request.method =='POST':
        try:
            price.title = request.POST['title']
            price.price = request.POST['price']
            price.body = request.POST['body']
            price.save()
            messages.success(request, 'Price muvaffaqqqiyatli o`zgartirildi')
        except:
            messages.error(request, 'Price o`zgartirishda xatolik')
        return redirect('dashboard:price_list')
    context = {
        'price':price
    }
    return render(request, 'dashboard/price/edit.html', context)


@login_required(login_url='dashboard:log_in')
def delete_price(request, id):
    try:
        models.Price.objects.get(id=id).delete()
        messages.error(request, 'Price muvaffaqqiyatli o`chirildi')
    except:
        messages.error(request, 'Price o`chirishda xatolik')
    return redirect('dashboard:price_list')


@login_required(login_url='dashboard:log_in')
def create_about(request):
    if request.method == "POST":
        try:
            body = request.POST['body']
            models.AboutUs.objects.create(
                body=body
            )
            messages.success(request, 'About Us muvaffaqqiyatli yaratildi')
        except:
            messages.error(request, 'About Us yaratishda xatolik')
    return render(request, 'dashboard/about/create.html')


@login_required(login_url='dashboard:log_in')
def list_about(request):
    about = models.AboutUs.objects.all()
    context = {
        'about':about
    }
    return render(request, 'dashboard/about/list.html', context)

@login_required(login_url='dashboard:log_in')
def detail_about(request, id):
    about = models.AboutUs.objects.get(id=id)
    context = {
        'about':about
    }
    return render(request, 'dashboard/about/detail.html', context)


@login_required(login_url='dashboard:log_in')
def edit_about(request, id):
    about = models.AboutUs.objects.get(id=id)
    if request.method =='POST':
        try:
            about.body = request.POST['body']
            about.save()
            messages.success(request, 'About Us muvaffaqqiyatli o`zgartirildi')
        except:
            messages.error(request, 'About Us o`zgartirishda xatolik')
        return redirect('dashboard:about_list')
    context = {
        'about':about
    }
    return render(request, 'dashboard/about/edit.html', context)

@login_required(login_url='dashboard:log_in')
def delete_about(request, id):
    try:
        models.AboutUs.objects.get(id=id).delete()
        messages.error(request, 'About Us muvaffaqqiyatli o`chirildi')
    except:
        messages.error(request, 'About Us o`chirishda xatolik')
    return redirect('dashboard:about_list')


@login_required(login_url='dashboard:log_in')
def list_contact(request):   
    contacts = models.Contact.objects.all()
    context = {
        'contacts':contacts
    }
    return render(request, 'dashboard/contact/list.html', context)


@login_required(login_url='dashboard:log_in')
def detail_contact(request, id):
    contacts = models.Contact.objects.get(id=id) 
    context = {
        'contacts':contacts
    }
    return render(request, 'dashboard/contact/detail.html', context)

@login_required(login_url='dashboard:log_in')
def edit_contact(request, id):
    contact = models.Contact.objects.get(id=id)
    if request.method == "POST":
        try:
            is_show = request.POST.get('is_show')  
            contact.is_show = is_show == 'on'
            contact.save()
            messages.success(request, 'Contactdagi ma`lumot muvaffaqqiyatli o`zgartirildi')
        except:
            messages.error(request, 'Ma`lumotni o`zgartirishda xatolik yuz berdi')
        return redirect('dashboard:contact_list')
    context = {
        'contact': contact, 
    }
    return render(request, 'dashboard/contact/edit.html', context)


# ------------------------------register, login, logout----------------------------
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_confirm = request.POST['password_confirm']
        if password == password_confirm:
            User.objects.create_user(
                username=username,

templates/dashboard/about/create.html
{% extends "dashboard/base.html" %}
{% block content  %}
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">                                    
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div><!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title">Ma'lumot qo'shish</h4>
                                        <p class="text-muted font-14"> Web saytning yuqori qismi
                                        </p>
                                        <div class="tab-content">
                                            <div class="tab-pane show active" id="typeahead-preview" role="tabpanel">
                                                <div class="row">
                                                    <form method="post">
                                                        {% csrf_token %}
                                                        <div class="col-lg-12">
                                                            <div class="mb-3">
                                                                <label class="form-label">Tana qism</label>
                                                                <span class="twitter-typeahead" style="position: relative; display: inline-block;">
                                                                    <textarea name="body" class="form-control tt-hint" cols="30" rows="10"></textarea>
                                                                    <pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: Nunito, sans-serif; font-size: 14.4px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div class="tt-dataset tt-dataset-states"></div></div></span>
                                                            </div>
                                                        </div> <!-- end col -->
                                                        </div> <!-- end col -->
                                                        <div class="col">
                                                            <button type="submit" class="btn btn-success rounded-pill">Success</button>
                                                        </div>
                                                        
                                                    </form>
                                                    </div><!-- end row -->                    
                                            </div> <!-- end preview-->
                                        </div> <!-- end tab-content-->
                                    </div> <!-- end card-body -->
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                        </div>
                    </div><!-- container -->
                </div><!-- content -->

{% endblock %}

templates/dashboard/about/detail.html
{% extends "dashboard/base.html" %}
{% block content  %}
            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">                                    
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <div class="d-flex justify-content-around align-items-center">
                                        <h4 class="page-title" style="display: inline;">Dashboard</h4>
                                        <a href="{% url 'dashboard:about_edit' about.id %}" class="btn btn-primary">O`zgartirish</a>
                                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#centermodal">O`chirish</button>
                                        <div class="modal fade" id="centermodal" tabindex="-1" role="dialog" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title" id="myCenterModalLabel">About Usni o`chirmoqchimisiz? </h4>
                                                        <form method="get" action="{% url 'dashboard:about_delete' about.id %}">
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <input type="checkbox" class="form-check-input" id="customCheckcolor7" required>
                                                            <label for="chkb">Ha</label> <br> <br>
                                                            <button type="button" class="btn btn-dark" data-bs-dismiss="modal" aria-hidden="true">Qaytish</button>
                                                            <button class="btn btn-danger" type="submit">O`chirish</button>
                                                        </div>
                                                        </form>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal-dialog -->
                                        </div><!-- /.modal -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                 <div class="card">
                                        <div class="card-body">
                                            <h4 class="header-title mb-3">Biz haqimizda batafsil</h4>
                
                                            <div class="table-responsive">
                                                <table class="table mb-0">
                                                    <thead class="table-light">
                                                    </thead>
                                                    <tbody>
                                                    <tr>
                                                        <td><strong>Batafsil</strong> :</td>
                                                        <td>{{about.body}}</td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </div><!-- end table-responsive -->
                                        </div>
                                    </div>
                                </div> <!-- end card-->
                            </div> <!-- end col -->
                        </div>
                    </div><!-- container -->
                </div><!-- content -->
{% endblock %}

templates/dashboard/about/list.html
{% extends "dashboard/base.html" %}
{% block content  %}
            <div class="content-page">
                <div class="content">
                    <!-- Start Content-->
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">                                    
                                    <div class="page-title-right">
                                        <form class="d-flex">
                                            <div class="input-group">
                                                <input type="text" class="form-control form-control-light" id="dash-daterange">
                                                <span class="input-group-text bg-primary border-primary text-white">
                                                    <i class="mdi mdi-calendar-range font-13"></i>
                                                </span>
                                            </div>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-2">
                                                <i class="mdi mdi-autorenew"></i>
                                            </a>
                                            <a href="javascript: void(0);" class="btn btn-primary ms-1">
                                                <i class="mdi mdi-filter-variant"></i>
                                            </a>
                                        </form>
                                    </div>
                                    <h4 class="page-title">Dashboard</h4>
                                </div>
                            </div>
                        </div><!-- end row -->
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-xl-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title">About Us ro'yxati</h4>
                                        <div class="tab-content">
                                            <div class="tab-pane show active" id="striped-rows-preview" role="tabpanel">
                                                <div class="table-responsive-sm">
                                                    <table class="table table-striped table-centered mb-0">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
                                                                <th>Tana Qism</th>
                                                                <th>Harakatlar</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for about in  about %}
                                                            <tr>
                                                                <td>{{forloop.counter}}</td>
                                                                <td>{{about.body}}</td>
                                                                <td class="table-action">
                                                                    <a href="{% url 'dashboard:about_detail' about.id %}" class="action-icon"> <i class=" ri-share-forward-2-line"></i></a>
                                                                </td>
                                                            </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div> <!-- end table-responsive-->                     
                                            </div> <!-- end preview-->
                                         </div> <!-- end tab-content-->
                                    </div> <!-- end card body-->
                                </div> <!-- end card -->
                            </div>
                        </div>
                    </div><!-- container -->
                </div><!-- content -->

{% endblock %}