Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls'))
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),

    #----------------------------banner-----------------------------------
    path('banner-list/', views.list_banner, name='banner_list'),
    path('banner-create/', views.create_banner, name='banner_create'),
    path('banner-detail/<int:id>/', views.detail_banner, name='banner_detail'),
    path('banner-edit/<int:id>/', views.edit_banner, name='banner_edit'),
    path('banner-delete/<int:id>/', views.delete_banner, name='banner_delete'),
    # ------------------------service----------------------------
    path('service-list/', views.list_service, name='service_list'),
    path('service-create/', views.create_service, name='service_create'),
    path('service-detail/<int:id>/', views.detail_service, name='service_detail'),
    path('service-edit/<int:id>/', views.edit_service, name='service_edit'),
    path('service-delete/<int:id>/', views.delete_service, name='service_delete'),
    #-----------------------price---------------------------------------
    path('price-list/', views.list_price, name='price_list'),
    path('price-create/', views.create_price, name='price_create'),
    path('price-detail/<int:id>/', views.detail_price, name='price_detail'),
    path('price-edit/<int:id>/', views.edit_price, name='price_edit'),
    path('price-delete/<int:id>/', views.delete_price, name='price_delete'),
    #--------------------------------about-------------------------------
    path('about-list/', views.list_about, name='about_list'),
    path('about-create/', views.create_about, name='about_create'),
    path('about-detail/<int:id>/', views.detail_about, name='about_detail'),
    path('about-edit/<int:id>/', views.edit_about, name='about_edit'),
    path('about-delete/<int:id>/', views.delete_about, name='about_delete'),
    #---------------------------------contact--------------------------------------
    path('contact-list/', views.list_contact, name='contact_list'),
    path ('contact-detail/<int:id>/', views.detail_contact, name='contact_detail'),
    path('contact-edit/<int:id>/', views.edit_contact, name='contact_edit'),
    # -----------------register, login, logout-------------------------------
    path('register/', views.register, name='register'),
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),
    # ----------------search--------------
    path('q', views.query, name='query')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('service/', views.service, name='service'),
    path('about/', views.about, name='about'),
    path('price/', views.price, name='price'),
]

templates/front/about.html
{% extends "front/base.html" %}
{% load static %}
{% block content %}

  <section class="about_section layout_padding">
    <div class="container  ">
      <div class="row">
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>{{about.body}}</p>        
              <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6 ">
          <div class="img-box">
            <img src="{% static 'front/images/about-img.png' %}" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock  %}
 

templates/front/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static 'front/images/fevicon.png' %}" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Hostit</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'front/css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

  <!-- font awesome style -->
  <link href="{% static 'front/css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'front/css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'front/css/responsive.css' %}" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'main:index' %}">
            <span>Hostit</span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ml-auto">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'main:index'%}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:about'%}"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:service'%}">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:price'%}">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:contact'%}">Contact Us</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

{% block content %}
{% endblock %}

<section class="info_section layout_padding2">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="info_contact">
          <h4>
            Address
          </h4>
          <div class="contact_link_box">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Location
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Call +998 99 999 99 99
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                example@gmail.com
              </span>
            </a>
          </div>
        </div>
        <div class="info_social">
          <a href="">
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </a>
          <a href="">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
          <a href="">
            <i class="fa fa-linkedin" aria-hidden="true"></i>
          </a>
          <a href="">
            <i class="fa fa-instagram" aria-hidden="true"></i>
          </a>
        </div>
      </div>
      <div class="col-md-3">
        <div class="info_link_box">
          <h4>
            Links
          </h4>
          <div class="info_links">
            <a class="active" href="{% url 'main:index' %}">
              <img src="{% static 'front/images/nav-bullet.png' %}" alt="">
              Home
            </a>
            <a class="" href="{% url 'main:about' %}">
              <img src="{% static 'front/images/nav-bullet.png' %}" alt="">
              About
            </a>
            <a class="" href="{% url 'main:service' %}">
              <img src="{% static 'front/images/nav-bullet.png' %}" alt="">
              Services
            </a>
            <a class="" href="{% url 'main:price' %}">
              <img src="{% static 'front/images/nav-bullet.png' %}" alt="">
              Pricing
            </a>
            <a class="" href="{% url 'main:contact' %}">
              <img src="{% static 'front/images/nav-bullet.png' %}" alt="">
              Contact Us
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="info_detail">
          <h4>
            Info
          </h4>
          <p>
            necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful
          </p>
        </div>
      </div>
      <div class="col-md-3 mb-0">
        <h4>
          Subscribe
        </h4>
        <form action="#">
          <input type="text" placeholder="Enter email" />
          <button type="submit">
            Subscribe
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

<!-- end info section -->


<!-- footer section -->
<footer class="footer_section">
  <div class="container">
    <p>
      &copy; <span id="displayYear"></span> All Rights Reserved By <b><i>Aziz.dev</i></b>
    </p>
  </div>
</footer>
<!-- footer section -->

<!-- jQery -->
<script src="{% static 'front/js/jquery-3.4.1.min.js' %}"></script>
<!-- bootstrap js -->
<script src="{% static 'front/js/bootstrap.js' %}"></script>
<!-- custom js -->
<script src="{% static 'front/js/custom.js' %}"></script>


</body>

</html>

templates/front/contact.html
{% extends "front/base.html" %}
{% block content %}

  <section class="contact_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Get In Touch
        </h2>
      </div>
      <div class="row">
        <div class="col-md-8 col-lg-6 mx-auto">
          <div class="form_container">
            <form method="post">
              {% csrf_token %}
              <div>
                <input type="text" placeholder="Your Name"  name="name"/>
              </div>
              <div>
                <input type="email" placeholder="Your Email" name="email" />
              </div>
              <div>
                <input type="text" placeholder="Your Phone" name="phone" />
              </div>
              <div>
                <input type="text" class="message-box" placeholder="Message" name="message" />
              </div>
              <div class="btn_box ">
                <button>
                  SEND
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/front/index.html
{% extends "front/base.html" %}
{% load static %}
{% block content %}
  <div class="hero_area">
    <!-- slider section -->
    <section class="slider_section fullscreen_slider">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="detail-box">
                    <h1>
                      {{baner.title}}
                    </h1>
                    <p>
                      {{baner.body}}</p>
                    <div class="btn-box">
                      <a href="{% url 'dashboard:register' %}" class="btn-1">
                        Register
                      </a>
                      <a href="{% url 'dashboard:log_in' %}" class="btn-1">
                        Login
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="row">
                    <div class=" col-lg-10 mx-auto">
                      <div class="img-box">
                        <img src="{% static 'front/images/slider-img.png' %}" alt="">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end slider section -->
  </div>
  <!-- service section -->

  <section class="service_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Our Services
        </h2>
      </div>
    </div>
    <div class="container ">
      <div class="row">
        {% for service in services %}
        <div class="col-md-6 col-lg-4">
          <div class="box ">
            <div class="img-box">
              <img src="{{service.icon.url}}" alt="">
            </div>
            <div class="detail-box">
              <h4>
                {{service.name}}
              </h4>
              <p>{{service.body}}</p>
              <a href="">
                Read More
                <i class="fa fa-long-arrow-right" aria-hidden="true"></i>

              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <!-- end service section -->

  <!-- about section -->

  <section class="about_section layout_padding-bottom">
    <div class="container  ">
      <div class="row">
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>
              {{about.body}}</p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6 ">
          <div class="img-box">
            <img src="{% static 'front/images/about-img.png' %}" alt="">
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- end about section -->


  <!-- server section -->

  <section class="server_section">
    <div class="container ">
      <div class="row">
        <div class="col-md-6">
          <div class="img-box">
            <img src="{% static 'front/images/server-img.jpg' %}" alt="">
            <div class="play_btn">
              <button>
                <i class="fa fa-play" aria-hidden="true"></i>
              </button>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                Let us manage your server
              </h2>
              <p>
                Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore
              </p>
            </div>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end server section -->

  <!-- price section -->

  <section class="price_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Our Pricing
        </h2>
      </div>
      <div class="price_container ">
        {% for price in prices %}
        <div class="box">
          <div class="detail-box">
            <h2>$ <span>{{price.price}}</span></h2>
            <h6>
              {{price.title}}
            </h6>
            <ul class="price_features">
                {% for i in price.body %}
                <li>
                    {{i}}
                </li>
                {% endfor %}
            </ul>
          </div>
          <div class="btn-box">
            <a href="">
              See Detail
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <!-- price section -->

  <!-- contact section -->
  <section class="contact_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Get In Touch
        </h2>
      </div>
      <div class="row">
        <div class="col-md-8 col-lg-6 mx-auto">
          <div class="form_container">
            <form method="post" action="{% url 'main:contact' %}">
                {% csrf_token %}
              <div>
                <input type="text" placeholder="Your Name" name="name" />
              </div>
              <div>
                <input type="email" placeholder="Your Email" name="email" />
              </div>
              <div>
                <input type="text" placeholder="Your Phone" name="phone" />
              </div>
              <div>
                <input type="text" class="message-box" placeholder="Message" name="message" />
              </div>
              <div class="btn_box ">
                <button>
                  SEND
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end contact section -->
{% endblock %}

  

templates/front/price.html
{% extends "front/base.html" %}
{% block content %}

  <section class="price_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Our Pricing
        </h2>
      </div>
      <div class="price_container ">
        {% for price in prices %}
        <div class="box">
          <div class="detail-box">
            <h2>$ <span>{{price.price}}</span></h2>
            <h6>
              {{price.title}}
            </h6>
            <ul class="price_features">
                {% for i in price.body %}
                <li>
                    {{i}}
                </li>
                {% endfor %}
            </ul>
          </div>
          <div class="btn-box">
            <a href="">
              See Detail
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

{% endblock %}

templates/front/service.html
{% extends "front/base.html" %}
{% block content %}
<section class="service_section layout_padding">
  <div class="container">
    <div class="heading_container heading_center">
      <h2>
        Our Services
      </h2>
    </div>
  </div>
  <div class="container ">
    <div class="row">
      {% for service in services %}
      <div class="col-md-6 col-lg-4">
        <div class="box ">
          <div class="img-box">
            <img src="{{service.icon.url}}" alt="">
          </div>
          <div class="detail-box">
            <h4>
              {{service.name}}
            </h4>
            <p>{{service.body}}</p>
            <a href="">
              Read More
              <i class="fa fa-long-arrow-right" aria-hidden="true"></i>

            </a>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</section>
{% endblock %}